### ISSUE TITLE
Controls the install and open icon in the address bar

### ISSUE THREAD

**Issue by hanguokai** [WICG/beforeinstallprompt#23]
<img width="333" alt="Screen Shot 2021-08-07 at 5 13 25 PM" src="https://user-images.githubusercontent.com/776467/128595371-08d4bbc8-dbf2-4331-a525-30634a771cb8.png">
<img width="340" alt="Screen Shot 2021-08-07 at 5 13 40 PM" src="https://user-images.githubusercontent.com/776467/128595373-72b0432c-f31d-43e6-8329-7826b35691e6.png">

As shown in the images above, the browser address bar has install icon and open icon for installing and launching the app. But not all web pages in the origin should be used for it. For example, help pages of the app should be opened as general web pages in the browser, rather than load them into the app.

So the website should controls whether the install and open icon is displayed for a page. For example control it by manifest or by javascript.

**Comment by meduzen** [comment]
I think we shouldn’t decide for the users: they should be free to open whatever page how they want.

Also, we already have the [Web Manifest scope](https://developer.mozilla.org/en-US/docs/Web/Manifest/scope) that can be used to limit the URL scope of an installable app.

In the use case you mention, if the help section is outside the Web Manifest scope, then the browser will threat it as an external website, if I’m correct.

**Comment by hanguokai** [comment]
I considered the scope. But it is not sufficient for all cases. For example, the landing page of the app is `/`. And there is an install button on the landing page. To make the install button work, the scope of the manifest and service worker should also be set `/`.

**Comment by hanguokai** [comment]
Generally, users don't know which part of pages in the origin can be loaded into the app. Developers know it.

**Comment by hanguokai** [comment]
Move this issue to https://github.com/w3c/manifest/issues/996 . I listed more behaviors of the install icon and launch icon https://github.com/w3c/manifest/issues/996#issuecomment-901948013 . But they are not clearly defined in the spec.
