### ISSUE TITLE
Control the default behavior after installation

### ISSUE THREAD

**Issue by hanguokai** [WICG/beforeinstallprompt#24]
Currently, after installation of a PWA app, Chrome browser loads current page into the app automatically. But not all web pages in the origin should be loaded into the app. For example, the landing page of the app introduce the application and show an install button. After installation, the app should be launched to it's start_url, not the landing page url.

So the website should be able to control the default behavior after installation. For example:

- don't launch the app after installation, stay on the current page, and supply a launchApp() method for developers.
- launch the app with start_url (not current url), and stay on the current page

**Comment by dmurph** [comment]
Can you actually file this on the manifest spec repo? This repository isn't for general manifest feature requests. These issues should only pertain to features that are in the incubations spec or in hosted explainers.
