### ISSUE TITLE
Dev interest in using Note-taking API - new note url

### ISSUE THREAD

**Issue by phoglenix** [WICG/beforeinstallprompt#25]
Hi web developers,

We would like to gauge interest in using the new_note_url member, as described in the [explainer](https://github.com/WICG/manifest-incubations/blob/gh-pages/note_taking-explainer.md) and [spec](https://wicg.github.io/manifest-incubations/index.html#note_taking-member).

If you are interested in potentially using the new note URL member, please reply to this thread, including your affiliation to a company or organisation or app, if any.

Thanks!

**Comment by kelvinkoko** [comment]
I am creator of [Stashany](https://www.stashany.com). Would like to support this proposal because I think it enhance note taking web app user experience. Also as state in the explainer, it will be great if it support "new note with content". I can imagine that one common use case is user would like to create new note with some text highlighted.

**Comment by bogacg** [comment]
I love PWA in general while the proposed solution seems solid a generalized interface (as pointed in [Alternatives Considered](https://github.com/WICG/manifest-incubations/blob/gh-pages/note_taking-explainer.md#alternatives-considered) section) would make more sense I think.

**Comment by phoglenix** [comment]
Thanks for the feedback!
bogacg@ are there any particular capabilities you would like to see in a more generalized interface?

**Comment by pavsidhu** [comment]
To piggybank off of @bogacg's comment, I think a generalized interface will prevent polluting the root object as I can imagine  more capabilities could be added. For example, productivity apps that manage calendars, reminders and notes and would probably appreciate grouping capabilities together (assuming calendar/reminder integrations may be added).

**Comment by Hengjie** [comment]
[Kami](https://www.kamiapp.com) would be interested. We have a stylus supported PWA used by millions of students and teachers. Many of them are on Chromebooks.

**Comment by alex-titarenko** [comment]
I'm the developer of NotesHub (https://noteshub.app/) PWA note-taking app. Currently quick-notes functionality is under development and this proposal will bring the real value for system integration. Looking forward for the change to happen.

**Comment by raevilman** [comment]
Totally interested in this! Thanks in advance 👍

---
PS: I am also building a note taking PWA, Last month only had implemented web share target API.

**Comment by phoglenix** [comment]
Thanks for all the expressions of interest! We have now received enough developer interest to ship the API 🎉 
Closing this issue, but you may still file issues / feature requests relating to the note-taking API on this repo.

**Comment by phoglenix** [comment]
Given that you're interested in this API, many of you might also be interested in (stylus) handwriting recognition API, that is currently in Origin Trial. They are also seeking expressions of interest from developers at https://github.com/WICG/handwriting-recognition/issues/21

Also, this API launched in Chrome M93! You can use it by simply adding `"note_taking": { "new_note_url": "/your_new_note_url.html" },` to your manifest :)
