### ISSUE TITLE
Scope extensions: incorporate manifest ID into the web-app-origin-association file

### ISSUE THREAD

**Issue by mandymsft** [WICG/beforeinstallprompt#39]
Should association files use [manifest ID](https://github.com/philloooo/pwa-unique-id/blob/main/explainer.md) instead of a link to identify web app?

**Comment by mandymsft** [comment]
Previous discussion: https://github.com/WICG/pwa-url-handler/issues/22

**Comment by LuHuangMSFT** [comment]
Manifest ID has been added to the scope extensions design and implemented.
